                                     # must accept EULA the first time that the image is started
# docker run splunk/baac_universalforwarder:6.4.4
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/bac_universalforwarder:6.4.4
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/bac_splunkuniversalforwarder:6.4.4 
version: '2'
services:
  vsplunk_uf:
    image: busybox
    volumes:
      - /banktools/splunkforwarder/etc
      - /banktools/splunkforwarder/var
  splunkuniversalforwarder:
#    build: .
    hostname: bac_splunkuniversalforwarder
    image: splunk/bac_universalforwarder:6.4.4
#    environment:
#      SPLUNK_START_ARGS: --accept-license
    volumes_from:
      - vsplunk_uf
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
